Don't use malloc.h on Unix for _mm_malloc()
On BSDs including malloc.h causes a warning/error while on GNU systems
it provides malloc(3) extensions but not of _mm-type which are specific
to compiler.

  /usr/include/malloc.h:3:2: error: "<malloc.h> has been replaced by <stdlib.h>"
  #error "<malloc.h> has been replaced by <stdlib.h>"
   ^

i386 without -march or -msse can hit another issue:

  src/Buffer.hpp:147:13: error: use of undeclared identifier '_mm_free'
              _mm_free(host_ptr);
              ^
  src/Buffer.hpp:282:24: error: use of undeclared identifier '_mm_malloc'
              host_ptr = _mm_malloc(byte_size, 64);
                         ^
  src/Buffer.hpp:314:24: error: use of undeclared identifier '_mm_malloc'
              host_ptr = _mm_malloc(byte_size, 64);
                         ^
  src/Buffer.hpp:325:24: error: use of undeclared identifier '_mm_malloc'
              host_ptr = _mm_malloc(byte_size, 64);
                         ^
  4 errors generated.